spring:
  datasource:
    url: jdbc:mysql://localhost:3306/LibraryManagementSystem?createDatabaseIfNotExist=true
    username: root
    password: mysql@anjali17
  jpa:
    hibernate.ddl-auto: update
    show-sql: true

server:
  port: 9090

custom_property:
  secret_key: fhcj1434

book:
  return:
    due_date: 14

